[package]
name = "safe"
version = "0.1.1"
description = "Simple Safe Network Client"
edition = "2021"

[dependencies]
tokio = "*"
bytes = { version = "1.0.1", features = ["serde"] }
serde = "1.0.130"
tracing = "*"
rand = "0.8.5"
xor_name = "5.0.0"

libp2p = { version="0.53", features = ["serde"] }
bls = { package = "blsttc", version = "8.0.1" }
tiny-keccak = { version = "*", features = [ "sha3" ] }

self_encryption = "*"
sn_client = "0.110.0"
sn_peers_acquisition = { version="0.5.0", features = ["network-contacts"] }
sn_logging = "0.2.33"
sn_transfers = "0.19.0"
sn_registers = "0.3.18"

[profile.dev]
debug = 0
strip = "debuginfo"
incremental = true
