[package]
name = "safe"
version = "0.2.2"
description = "Simple Safe Network Client"
edition = "2021"

[dependencies]
tokio = "*"
bytes = { version = "*", features = ["serde"] }
tracing = "*"
rand = "0.8.5"
xor_name = "*"
libp2p = { version="*", features = ["serde"] }
bls = { package = "blsttc", version = "*" }
alloy-primitives = "*"
rmp-serde = "*"

ant-logging = "*"
autonomi = { version = "0.4.2", features = ["loud"] }
evmlib = "*"
ant-protocol = "*"

[profile.dev]
debug = 0
strip = "debuginfo"
incremental = true
