[package]
name = "safe"
version = "0.1.9"
description = "Simple Safe Network Client"
edition = "2021"

[dependencies]
tokio = "*"
bytes = { version = "1.0.1", features = ["serde"] }
serde = "1.0.130"
tracing = "*"
rand = "0.8.5"
xor_name = "5.0.0"

libp2p = { version="0.53", features = ["serde"] }
bls = { package = "blsttc", version = "8.0.1" }
tiny-keccak = { version = "*", features = [ "sha3" ] }
hex = "*"
url = "*"
alloy-primitives = "*"

ant-logging = "*"
ant-registers = "*"
autonomi = { version = "0.3.4", features = ["local", "full", "loud"] }
evmlib = "*"
ant-protocol = "*"

[profile.dev]
debug = 0
strip = "debuginfo"
incremental = true
