[package]
name = "safe"
version = "0.1.1"
description = "Simple Safe Network Client"
edition = "2021"

[dependencies]
tokio = "*"
bytes = { version = "1.0.1", features = ["serde"] }
serde = "1.0.130"
tracing = "*"
rand = "0.8.5"
xor_name = "5.0.0"

libp2p = { version="0.53", features = ["serde"] }
bls = { package = "blsttc", version = "8.0.1" }
tiny-keccak = { version = "*", features = [ "sha3" ] }

self_encryption = "*"
#sn_client = { path = "../github/safe_network/sn_client" }
sn_peers_acquisition = { path="../github/safe_network/sn_peers_acquisition", features = ["network-contacts"] }
sn_logging = { path = "../github/safe_network/sn_logging" }
#sn_transfers = { path = "../github/safe_network/sn_transfers" }
sn_registers = { path = "../github/safe_network/sn_registers" }
autonomi = { path = "../github/safe_network/autonomi", features = ["local", "full"] }
evmlib = { path = "../github/safe_network/evmlib" }
alloy-primitives = "*"

[profile.dev]
debug = 0
strip = "debuginfo"
incremental = true
